name: CI Pipeline

on:
  push:
    branches:
      - master
      - jest-setup
  pull_request:
    branches:
      - master
      - jest-setup

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Sjekk ut koden fra repositoriet
      uses: actions/checkout@v3

    - name: Sett opp Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16

    - name: Gå til client-mappen
      working-directory: client
      run: echo "Navigerer til client-mappen"

    - name: Installer avhengigheter
      working-directory: client
      run: npm install

    - name: Kjør tester
      working-directory: client
      run: npm test